name: naggingnelly
description: A PA for Procrastinators
version: 0.0.1+7
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  badges: ^3.1.2
  bloc: ^8.1.3
  cloud_firestore: ^4.17.0
  equatable: ^2.0.5
  firebase_analytics: ^10.10.2
  firebase_auth: ^4.19.5
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  firestore_todos_api:
    path: packages/firestore_todos_api
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  global_configuration: ^2.0.0
  google_sign_in: ^6.2.1
  humanize_duration: ^0.0.2
  intl: ^0.18.1
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  shared_preferences: ^2.2.3
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository
  uuid: ^4.4.0

dev_dependencies:
  bloc_test: ^9.1.6
  dart_pre_commit: ^5.3.0
  flutter_test:
    sdk: flutter
  git_hooks: ^1.0.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

dart_pre_commit:
  pull-up-dependencies: false
  outdated: false
