name: naggingnelly
description: A PA for Procrastinators
version: 0.0.1+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  firebase_analytics: ^10.10.2
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.6
  dart_pre_commit: ^5.3.0
  flutter_test:
    sdk: flutter
  git_hooks: ^1.0.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
