// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_productio.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYwHgjpy2IpJrr0x4MqjRzdwJrepJWVlM',
    appId: '1:52841464896:web:59a925a839f9a61345cba5',
    messagingSenderId: '52841464896',
    projectId: 'naggingnelly-prod',
    authDomain: 'naggingnelly-prod.firebaseapp.com',
    storageBucket: 'naggingnelly-prod.appspot.com',
    measurementId: 'G-V8GYKQ1DF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ3-g9QYFzXsnRDP4cqKBMS7L8S8VpQg4',
    appId: '1:52841464896:android:65859d57dc68a6fa45cba5',
    messagingSenderId: '52841464896',
    projectId: 'naggingnelly-prod',
    storageBucket: 'naggingnelly-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJyQOKTRKfC9xz_7FTbsu0T6A7jACii98',
    appId: '1:52841464896:ios:fe956ad800938b8f45cba5',
    messagingSenderId: '52841464896',
    projectId: 'naggingnelly-prod',
    storageBucket: 'naggingnelly-prod.appspot.com',
    androidClientId:
        '52841464896-7nb5rmj1lkk0csiiun3tpmv84389t7i8.apps.googleusercontent.com',
    iosClientId:
        '52841464896-asrtqti0p06727j6776e31k6oeu7dger.apps.googleusercontent.com',
    iosBundleId: 'io.freedman.naggingnelly.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJyQOKTRKfC9xz_7FTbsu0T6A7jACii98',
    appId: '1:52841464896:ios:a3d4fd79a1b4124d45cba5',
    messagingSenderId: '52841464896',
    projectId: 'naggingnelly-prod',
    storageBucket: 'naggingnelly-prod.appspot.com',
    androidClientId:
        '52841464896-7nb5rmj1lkk0csiiun3tpmv84389t7i8.apps.googleusercontent.com',
    iosClientId:
        '52841464896-4fpf3ni4lgcdqrb1va51q1u98lqs9n7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYwHgjpy2IpJrr0x4MqjRzdwJrepJWVlM',
    appId: '1:52841464896:web:0ac49f39c2d565e745cba5',
    messagingSenderId: '52841464896',
    projectId: 'naggingnelly-prod',
    authDomain: 'naggingnelly-prod.firebaseapp.com',
    storageBucket: 'naggingnelly-prod.appspot.com',
    measurementId: 'G-GQEH31WJ9C',
  );
}
