// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkKr9u6wkA9splBzHcTM1nsve9jIrtlM0',
    appId: '1:350365535909:web:ecae3499e4a324dee5c74c',
    messagingSenderId: '350365535909',
    projectId: 'naggingnelly-staging',
    authDomain: 'naggingnelly-staging.firebaseapp.com',
    storageBucket: 'naggingnelly-staging.appspot.com',
    measurementId: 'G-PX9R6GBDFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQG4ax1MTbaJyDvRsNbXXxALWy5G4CmU',
    appId: '1:350365535909:android:39484c71d37f9bcbe5c74c',
    messagingSenderId: '350365535909',
    projectId: 'naggingnelly-staging',
    storageBucket: 'naggingnelly-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90w6kFHZhDR9NAiO3XC-xZ-ogD1lTf54',
    appId: '1:350365535909:ios:8960e4a34fdb87aae5c74c',
    messagingSenderId: '350365535909',
    projectId: 'naggingnelly-staging',
    storageBucket: 'naggingnelly-staging.appspot.com',
    iosBundleId: 'io.freedman.naggingnelly.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90w6kFHZhDR9NAiO3XC-xZ-ogD1lTf54',
    appId: '1:350365535909:ios:5b55a4ec41b33516e5c74c',
    messagingSenderId: '350365535909',
    projectId: 'naggingnelly-staging',
    storageBucket: 'naggingnelly-staging.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkKr9u6wkA9splBzHcTM1nsve9jIrtlM0',
    appId: '1:350365535909:web:11bb90e69b3d3291e5c74c',
    messagingSenderId: '350365535909',
    projectId: 'naggingnelly-staging',
    authDomain: 'naggingnelly-staging.firebaseapp.com',
    storageBucket: 'naggingnelly-staging.appspot.com',
    measurementId: 'G-MMYYDBP0SV',
  );

}