name: firestore_todos_api
description: A Flutter implementation of the TodosApi that uses Firestore.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.2
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  todos_api:
    path: ../todos_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
