name: Deploy to Firebase App Distribution

on: [push]

jobs:
  testflight:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk lib/main_production.dart --flavor production --release

      - name: Decode keystore
        env:
          ANDROID_KEYSTORE_CONTENT: ${{ secrets.ANDROID_KEYSTORE_CONTENT }}
        run: base64 -d "ANDROID_KEYSTORE_CONTENT" > android/keystore

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        env:
          ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk
